### ISSUE TITLE
Need const

### ISSUE THREAD

**Issue by kotbauk** [kirpichik/Parallels#1]
You need more "const" in definition of the functions

**Comment by kirpichik** [comment]
You can improve the quality of the code by creating a pull request.
This is done very simply:
1. Fork (next to the Star button that you already clicked)
2. Editing the code and adding the necessary structures to you
3. Create a pull request back to me in the repository
4. If everything is fine in your fixes, I accept the changes
In this way, you can improve the quality of Open Source and the overall Open Source community.
Thanks!

**Comment by dimonchik0036** [comment]
Соглашусь с овнером.

**Comment by kotbauk** [comment]
THANK YOU, SIR.
