### ISSUE TITLE
Needless memset

### ISSUE THREAD

**Issue by kotbauk** [kirpichik/Parallels#2]
https://github.com/kirpichik/Parallels/blob/e2fc84d34e82037b94cc37b7c53ac6f8e6f0f02a/lab4/solve.cpp#L45

This memset is needless, because the new operator initializes the array default value(for double type it's 0.0)
http://en.cppreference.com/w/cpp/language/new
http://en.cppreference.com/w/cpp/language/default_initialization

**Comment by kirpichik** [comment]
This memset is left as an additional reminder to TODO.
In this block, in the future, it is planned to add initialization with other initial values.

**Comment by kotbauk** [comment]
Thx for answer, man. I didn't understand, because my Russian isn't very good:grin:

**Comment by kirpichik** [comment]
No problem, dude.
Thank u for ur attentiveness.
